spring.datasource.url=jdbc:postgresql://ep-green-shape-a1wkuxej-pooler.ap-southeast-1.aws.neon.tech/neondb?prepareThreshold=0&preparedStatementCacheQueries=0
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fHK7yjcaL3Mr
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false

# Connection pool (HikariCP) - helps prevent stale plans
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000